// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2GO_EXE_Project.DAL.Context;

#nullable disable

namespace _2GO_EXE_Project.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251223134527_RefactorEscrowOrderPayment")]
    partial class RefactorEscrowOrderPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ActivityLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId")
                        .HasName("PK__Activity__5E5486480DB36993");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.AiModerationLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId")
                        .HasName("PK__AiModera__5E5486480174A9B8");

                    b.HasIndex("ListingId");

                    b.ToTable("AiModerationLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.AiScanResult", b =>
                {
                    b.Property<long>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ScanId"));

                    b.Property<string>("CategoryPrediction")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("NudityScore")
                        .HasColumnType("float");

                    b.Property<decimal?>("PriceEstimation")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<double?>("ScamScore")
                        .HasColumnType("float");

                    b.Property<double?>("SpamScore")
                        .HasColumnType("float");

                    b.HasKey("ScanId")
                        .HasName("PK__AiScanRe__63B32681BFCE5E87");

                    b.HasIndex("ListingId");

                    b.ToTable("AiScanResults");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ApiLog", b =>
                {
                    b.Property<long>("ApiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApiId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Endpoint")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("int");

                    b.HasKey("ApiId")
                        .HasName("PK__ApiLogs__024B3BB3924051E4");

                    b.ToTable("ApiLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0B23FCD2DD");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Chat", b =>
                {
                    b.Property<long>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("User1Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("User2Id")
                        .HasColumnType("bigint");

                    b.HasKey("ChatId")
                        .HasName("PK__Chats__A9FBE7C6633500B5");

                    b.HasIndex("User1Id");

                    b.HasIndex("User2Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21B76C2FE3969");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.DeviceLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LogId")
                        .HasName("PK__DeviceLo__5E5486484AA0DD95");

                    b.HasIndex("UserId");

                    b.ToTable("DeviceLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("DistrictId")
                        .HasName("PK__District__85FDA4C64D9546B6");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.EscrowContract", b =>
                {
                    b.Property<long>("EscrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EscrowId"));

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("EscrowId")
                        .HasName("PK__EscrowCo__557665D406EDB275");

                    b.HasIndex("BuyerId");

                    b.HasIndex("ListingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("SellerId");

                    b.ToTable("EscrowContracts");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.EscrowTransaction", b =>
                {
                    b.Property<long>("TxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TxId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("EscrowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TxId")
                        .HasName("PK__EscrowTr__F9FA65FC96EF3600");

                    b.HasIndex("EscrowId");

                    b.ToTable("EscrowTransactions");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime?>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("FixerUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RequestId")
                        .HasColumnType("bigint");

                    b.HasKey("AssignmentId")
                        .HasName("PK__FixerAss__32499E77DDD307A5");

                    b.HasIndex("FixerUserId");

                    b.HasIndex("RequestId");

                    b.ToTable("FixerAssignments");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RequestId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServiceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RequestId")
                        .HasName("PK__FixerReq__33A8517AE1259366");

                    b.HasIndex("ListingId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("FixerRequests");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerService", b =>
                {
                    b.Property<long>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ServiceId"));

                    b.Property<decimal?>("BasePrice")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ServiceId")
                        .HasName("PK__FixerSer__C51BB00AD5B142A7");

                    b.ToTable("FixerServices");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Listing", b =>
                {
                    b.Property<long>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ListingId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("HasNegotiation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ListingId")
                        .HasName("PK__Listings__BF3EBED0512A61BA");

                    b.HasIndex("SellerId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("WardId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingAttribute", b =>
                {
                    b.Property<long>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttributeId"));

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("AttributeId")
                        .HasName("PK__ListingA__C18929EA80D4FC97");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingAttributes");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingImage", b =>
                {
                    b.Property<long>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImageId"));

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.HasKey("ImageId")
                        .HasName("PK__ListingI__7516F70C45586241");

                    b.HasIndex("ListingId");

                    b.ToTable("ListingImages");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingView", b =>
                {
                    b.Property<long>("ViewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ViewId"));

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ViewedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("ViewId")
                        .HasName("PK__ListingV__1E371CF66220BD28");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("ListingViews");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MessageId"));

                    b.Property<long?>("ChatId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<long?>("SenderId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__C87C0C9C5FC829B3");

                    b.HasIndex("ChatId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Order", b =>
                {
                    b.Property<long>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderId"));

                    b.Property<long?>("BuyerId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("EscrowId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("SellerId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BCF29ADB7E0");

                    b.HasIndex("BuyerId");

                    b.HasIndex("EscrowId");

                    b.HasIndex("ListingId");

                    b.HasIndex("SellerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.OrderItem", b =>
                {
                    b.Property<long>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("OrderItemId"));

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__57ED0681BACC3EC9");

                    b.HasIndex("ListingId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Payment", b =>
                {
                    b.Property<long>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PaymentId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Method")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReferenceCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A383AF28E0A");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.PaymentLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("RawResponse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId")
                        .HasName("PK__PaymentL__5E548648A3C99DC5");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.PointTransaction", b =>
                {
                    b.Property<long>("TxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TxId"));

                    b.Property<int?>("ChangeAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TxId")
                        .HasName("PK__PointTra__F9FA65FCC8C19C20");

                    b.HasIndex("UserId");

                    b.ToTable("PointTransactions");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.RefreshToken", b =>
                {
                    b.Property<long>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefreshTokenId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ReportId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ReporterId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("TargetUserId")
                        .HasColumnType("bigint");

                    b.HasKey("ReportId")
                        .HasName("PK__Reports__D5BD4805096823C8");

                    b.HasIndex("ListingId");

                    b.HasIndex("ReporterId");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SavedListing", b =>
                {
                    b.Property<long>("SavedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SavedId"));

                    b.Property<long?>("ListingId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SavedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SavedId")
                        .HasName("PK__SavedLis__0B058FDCCF45C708");

                    b.HasIndex("ListingId");

                    b.HasIndex("UserId");

                    b.ToTable("SavedListings");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SearchHistory", b =>
                {
                    b.Property<long>("SearchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SearchId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Filters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Query")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("SearchId")
                        .HasName("PK__SearchHi__21C535F47026F753");

                    b.HasIndex("UserId");

                    b.ToTable("SearchHistory");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ShippingRequest", b =>
                {
                    b.Property<long>("ShipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShipId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("DeliveryAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<string>("PickupAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TrackingCode")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ShipId")
                        .HasName("PK__Shipping__2A05CAB3FA7A5C07");

                    b.HasIndex("OrderId");

                    b.ToTable("ShippingRequests");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("SubCategoryId")
                        .HasName("PK__SubCateg__26BE5B1941E8BD81");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SupportTicket", b =>
                {
                    b.Property<long>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TicketId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Topic")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("TicketId")
                        .HasName("PK__SupportT__712CC6074908E846");

                    b.HasIndex("UserId");

                    b.ToTable("SupportTickets");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime?>("BanUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Salt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C13494ED7");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserDevice", b =>
                {
                    b.Property<long>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DeviceId"));

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Ipaddress")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IPAddress");

                    b.Property<DateTime?>("LastActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("DeviceId")
                        .HasName("PK__UserDevi__49E123115414FA0C");

                    b.HasIndex("UserId");

                    b.ToTable("UserDevices");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserPoint", b =>
                {
                    b.Property<long>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PointId"));

                    b.Property<int?>("CurrentPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("LifetimePoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Tier")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PointId")
                        .HasName("PK__UserPoin__40A977E1BE40A65C");

                    b.HasIndex("UserId");

                    b.ToTable("UserPoints");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserProfile", b =>
                {
                    b.Property<long>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProfileId"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("WardId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId")
                        .HasName("PK__UserProf__290C88E40622A657");

                    b.HasIndex("UserId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserRating", b =>
                {
                    b.Property<long>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RatingId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<long?>("RatedUserId")
                        .HasColumnType("bigint");

                    b.Property<long?>("RaterId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("RatingId")
                        .HasName("PK__UserRati__FCCDF87C065FCA12");

                    b.HasIndex("RatedUserId");

                    b.HasIndex("RaterId");

                    b.ToTable("UserRatings");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserVerification", b =>
                {
                    b.Property<long>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationId"));

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("IdCardBackUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IdCardFrontUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VerificationId")
                        .HasName("PK__UserVeri__306D490791FA9ECD");

                    b.HasIndex("UserId");

                    b.ToTable("UserVerification");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.VerificationCode", b =>
                {
                    b.Property<long>("VerificationCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VerificationCodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("VerificationCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationCodes");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Ward", b =>
                {
                    b.Property<int>("WardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WardId"));

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("WardId")
                        .HasName("PK__Wards__C6BD9BCAC40737D0");

                    b.HasIndex("DistrictId");

                    b.ToTable("Wards");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ActivityLog", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ActLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.AiModerationLog", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("AiModerationLogs")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_AiLogs_Listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.AiScanResult", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("AiScanResults")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_AiScan_Listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Chat", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User1")
                        .WithMany("ChatUser1s")
                        .HasForeignKey("User1Id")
                        .HasConstraintName("FK_Chat_User1");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User2")
                        .WithMany("ChatUser2s")
                        .HasForeignKey("User2Id")
                        .HasConstraintName("FK_Chat_User2");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.DeviceLog", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("DeviceLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_DeviceLogs_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.District", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Districts_Cities");

                    b.Navigation("City");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.EscrowContract", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Buyer")
                        .WithMany("EscrowContractBuyers")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_Escrow_Buyer");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("EscrowContracts")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_Escrow_Listing");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Order", "Order")
                        .WithMany("EscrowContracts")
                        .HasForeignKey("OrderId");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Payment", "Payment")
                        .WithMany("EscrowContracts")
                        .HasForeignKey("PaymentId");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Seller")
                        .WithMany("EscrowContractSellers")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_Escrow_Seller");

                    b.Navigation("Buyer");

                    b.Navigation("Listing");

                    b.Navigation("Order");

                    b.Navigation("Payment");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.EscrowTransaction", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.EscrowContract", "Escrow")
                        .WithMany("EscrowTransactions")
                        .HasForeignKey("EscrowId")
                        .HasConstraintName("FK_EscrowTx_Escrow");

                    b.Navigation("Escrow");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerAssignment", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "FixerUser")
                        .WithMany("FixerAssignments")
                        .HasForeignKey("FixerUserId")
                        .HasConstraintName("FK_Assign_User");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.FixerRequest", "Request")
                        .WithMany("FixerAssignments")
                        .HasForeignKey("RequestId")
                        .HasConstraintName("FK_Assign_Request");

                    b.Navigation("FixerUser");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerRequest", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("FixerRequests")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_FixerReq_Listings");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.FixerService", "Service")
                        .WithMany("FixerRequests")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_FixerReq_Service");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("FixerRequests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_FixerReq_Users");

                    b.Navigation("Listing");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Listing", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Seller")
                        .WithMany("Listings")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_Listings_Users");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.SubCategory", "SubCategory")
                        .WithMany("Listings")
                        .HasForeignKey("SubCategoryId")
                        .HasConstraintName("FK_Listings_SubCat");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Ward", "Ward")
                        .WithMany("Listings")
                        .HasForeignKey("WardId")
                        .HasConstraintName("FK_Listings_Wards");

                    b.Navigation("Seller");

                    b.Navigation("SubCategory");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingAttribute", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("ListingAttributes")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_ListingAttributes_Listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingImage", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("ListingImages")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_ListingImages_Listings");

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ListingView", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("ListingViews")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_ListingViews_Listings");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("ListingViews")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_ListingViews_Users");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Message", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .HasConstraintName("FK_Messages_Chat");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK_Messages_Sender");

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Order", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Buyer")
                        .WithMany("OrderBuyers")
                        .HasForeignKey("BuyerId")
                        .HasConstraintName("FK_Orders_Buyer");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.EscrowContract", "Escrow")
                        .WithMany("Orders")
                        .HasForeignKey("EscrowId")
                        .HasConstraintName("FK_Orders_Escrow");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("Orders")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_Orders_Listing");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Seller")
                        .WithMany("OrderSellers")
                        .HasForeignKey("SellerId")
                        .HasConstraintName("FK_Orders_Seller");

                    b.Navigation("Buyer");

                    b.Navigation("Escrow");

                    b.Navigation("Listing");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.OrderItem", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("OrderItems")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_OrderItems_Listing");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_OrderItems_Orders");

                    b.Navigation("Listing");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Payment", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Payments_Users");

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.PaymentLog", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Payment", "Payment")
                        .WithMany("PaymentLogs")
                        .HasForeignKey("PaymentId")
                        .HasConstraintName("FK_PaymentLogs_Payments");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.PointTransaction", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("PointTransactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_PointTx_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.RefreshToken", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RefreshTokens_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Report", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("Reports")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_Reports_Listing");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Reporter")
                        .WithMany("ReportReporters")
                        .HasForeignKey("ReporterId")
                        .HasConstraintName("FK_Reports_Reporter");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "TargetUser")
                        .WithMany("ReportTargetUsers")
                        .HasForeignKey("TargetUserId")
                        .HasConstraintName("FK_Reports_Target");

                    b.Navigation("Listing");

                    b.Navigation("Reporter");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SavedListing", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Listing", "Listing")
                        .WithMany("SavedListings")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_SavedListings_Listings");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("SavedListings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_SavedListings_Users");

                    b.Navigation("Listing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SearchHistory", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_SearchHistory_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.ShippingRequest", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Order", "Order")
                        .WithMany("ShippingRequests")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Shipping_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SubCategory", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_SubCategories_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SupportTicket", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("SupportTickets")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Tickets_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserDevice", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserDevices_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserPoint", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("UserPoints")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserPoints_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserProfile", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("UserProfiles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserProfiles_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserRating", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "RatedUser")
                        .WithMany("UserRatingRatedUsers")
                        .HasForeignKey("RatedUserId")
                        .HasConstraintName("FK_UserRatings_Rated");

                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "Rater")
                        .WithMany("UserRatingRaters")
                        .HasForeignKey("RaterId")
                        .HasConstraintName("FK_UserRatings_Rater");

                    b.Navigation("RatedUser");

                    b.Navigation("Rater");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.UserVerification", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("UserVerifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserVer_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.VerificationCode", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.User", "User")
                        .WithMany("VerificationCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VerificationCodes_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Ward", b =>
                {
                    b.HasOne("_2GO_EXE_Project.DAL.Entities.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("DistrictId")
                        .HasConstraintName("FK_Wards_Districts");

                    b.Navigation("District");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.EscrowContract", b =>
                {
                    b.Navigation("EscrowTransactions");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerRequest", b =>
                {
                    b.Navigation("FixerAssignments");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.FixerService", b =>
                {
                    b.Navigation("FixerRequests");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Listing", b =>
                {
                    b.Navigation("AiModerationLogs");

                    b.Navigation("AiScanResults");

                    b.Navigation("EscrowContracts");

                    b.Navigation("FixerRequests");

                    b.Navigation("ListingAttributes");

                    b.Navigation("ListingImages");

                    b.Navigation("ListingViews");

                    b.Navigation("OrderItems");

                    b.Navigation("Orders");

                    b.Navigation("Reports");

                    b.Navigation("SavedListings");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Order", b =>
                {
                    b.Navigation("EscrowContracts");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("ShippingRequests");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Payment", b =>
                {
                    b.Navigation("EscrowContracts");

                    b.Navigation("PaymentLogs");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.SubCategory", b =>
                {
                    b.Navigation("Listings");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("ChatUser1s");

                    b.Navigation("ChatUser2s");

                    b.Navigation("DeviceLogs");

                    b.Navigation("EscrowContractBuyers");

                    b.Navigation("EscrowContractSellers");

                    b.Navigation("FixerAssignments");

                    b.Navigation("FixerRequests");

                    b.Navigation("ListingViews");

                    b.Navigation("Listings");

                    b.Navigation("Messages");

                    b.Navigation("OrderBuyers");

                    b.Navigation("OrderSellers");

                    b.Navigation("Payments");

                    b.Navigation("PointTransactions");

                    b.Navigation("RefreshTokens");

                    b.Navigation("ReportReporters");

                    b.Navigation("ReportTargetUsers");

                    b.Navigation("SavedListings");

                    b.Navigation("SearchHistories");

                    b.Navigation("SupportTickets");

                    b.Navigation("UserDevices");

                    b.Navigation("UserPoints");

                    b.Navigation("UserProfiles");

                    b.Navigation("UserRatingRatedUsers");

                    b.Navigation("UserRatingRaters");

                    b.Navigation("UserVerifications");

                    b.Navigation("VerificationCodes");
                });

            modelBuilder.Entity("_2GO_EXE_Project.DAL.Entities.Ward", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
